expected_db = [{'composer': 'The Lord of the Loop',
  'history': 'Tune made in a dark algorithmic night',
  'index': 1,
  'key': 'C',
  'melody': [(0, 8),
             (2, 4),
             (4, 4),
             (2, 8),
             (4, 2),
             (3, 2),
             (2, 4),
             (2, 6),
             (1, 6),
             (6, 4)],
  'meter': (4, 4),
  'origin': 'Trento',
  'title': 'Algorave'},
 {'composer': 'Matrix Queen',
  'history': 'Tune made in a dark algorithmic night',
  'index': 2,
  'key': 'G',
  'melody': [(5, 4),
             (6, 8),
             (4, 8),
             (4, 2),
             (5, 2),
             (0, 4),
             (1, 4),
             (3, 4),
             (3, 6),
             (4, 6),
             (2, 6),
             (2, 6)],
  'meter': (3, 4),
  'origin': 'Trento',
  'title': 'Transpose Your Head'},
 {'composer': 'anonymous truck driver',
  'history': 'Tune made in a dark algorithmic night',
  'index': 3,
  'key': 'E',
  'melody': [(6, 4),
             (1, 4),
             (3, 8),
             (3, 6),
             (4, 4),
             (4, 4),
             (3, 2),
             (6, 6),
             (1, 6),
             (6, 4)],
  'meter': (4, 4),
  'origin': 'Trento',
  'title': 'Pedal to the Metal'}]