expected_db2 = [{'composer': 'Drum Shaman',
  'discography': 'Sounds from the Jungle, 1968',
  'history': 'Folk songs collected while travelling',
  'index': 1,
  'key': 'E',
  'melody': [(6, 2),
             (6, 4),
             (6, 2),
             (6, 2),
             (0, 2),
             (4, 4),
             (4, 2),
             (4, 2),
             (3, 12)],
  'meter': (4, 4),
  'title': 'Jungle Beat'},
 {'composer': 'The Crazy Gipsy',
  'history': 'Folk songs collected while travelling',
  'index': 2,
  'key': 'G',
  'melody': [(0, 6), (0, 6), (6, 4), (4, 6), (0, 6), (6, 4)],
  'meter': (2, 4),
  'title': 'Byte Polka'}]