expected_movies_db = {'Q1062054': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1980, 1, 1),
              'names': {'de': 'Der Supercop',
                        'en': 'Super Fuzz',
                        'it': 'Poliziotto superpiù'}},
 'Q1070548': {'actors': [('Q221074', 'Bud Spencer'),
                         ('Q243430', 'Terence Hill')],
              'first_release': (1967, 10, 31),
              'names': {'de': 'Gott vergibt… Django nie!',
                        'en': "God Forgives... I Don't!",
                        'it': 'Dio perdona... io no!'}},
 'Q1131511': {'actors': [('Q221074', 'Bud Spencer')],
              'first_release': (1969, 10, 16),
              'names': {'de': 'Die fünf Gefürchteten',
                        'en': 'The Five Man Army',
                        'it': 'Un esercito di 5 uomini'}},
 'Q116187': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1983, 2, 11),
             'names': {'de': 'Bud, der Ganovenschreck',
                       'en': 'Thieves and Robbers',
                       'it': 'Cane e gatto'}},
 'Q1163902': {'actors': [('Q221074', 'Bud Spencer'),
                         ('Q243430', 'Terence Hill')],
              'first_release': (1951, 1, 1),
              'names': {'de': 'Das große Ferienabenteuer',
                        'en': 'Vacanze col gangster',
                        'it': 'Vacanze col gangster'}},
 'Q1192601': {'actors': [('Q221074', 'Bud Spencer')],
              'first_release': (1982, 8, 5),
              'names': {'de': 'Der Bomber', 'en': 'Bomber', 'it': 'Bomber'}},
 'Q1198395': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1969, 1, 1),
              'names': {'de': 'Der blauäugige Bandit',
                        'en': 'Barbagia',
                        'it': 'Barbagia'}},
 'Q1215151': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1966, 1, 1),
              'names': {'de': 'Die Nibelungen',
                        'en': 'Die Nibelungen',
                        'it': ''}},
 'Q1233715': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (2009, 1, 1),
              'names': {'de': 'Doc West – Nobody ist zurück',
                        'en': 'Doc West',
                        'it': 'Doc West'}},
 'Q1255585': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1965, 1, 1),
              'names': {'de': 'Ruf der Wälder',
                        'en': 'Call of the Forest',
                        'it': 'Il magnifico emigrante'}},
 'Q1295110': {'actors': [('Q221074', 'Bud Spencer')],
              'first_release': (1968, 3, 28),
              'names': {'de': 'Heute ich… morgen Du!',
                        'en': 'Oggi a me... domani a te!',
                        'it': 'Oggi a me... domani a te!'}},
 'Q1351744': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (2011, 1, 1),
              'names': {'de': 'Die Bergpolizei – Ganz nah am Himmel',
                        'en': 'Un passo dal cielo',
                        'it': 'Un passo dal cielo'}},
 'Q1420968': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1972, 4, 7),
              'names': {'de': 'Allein gegen das Gesetz',
                        'en': 'The Hassled Hooker',
                        'it': 'Il vero e il falso'}},
 'Q1423362': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1971, 1, 1),
              'names': {'de': 'McCabe & Mrs. Miller',
                        'en': 'McCabe & Mrs. Miller',
                        'it': 'I compari'}},
 'Q1497343': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1965, 1, 1),
              'names': {'de': 'Schüsse im 3/4 Takt',
                        'en': 'Shots in Threequarter Time',
                        'it': 'Operazione terzo uomo'}},
 'Q1571469': {'actors': [('Q221074', 'Bud Spencer')],
              'first_release': (1971, 1, 1),
              'names': {'de': 'Halleluja… Amigo',
                        'en': 'It Can Be Done Amigo',
                        'it': 'Si può fare... amigo'}},
 'Q1576167': {'actors': [('Q221074', 'Bud Spencer'),
                         ('Q243430', 'Terence Hill')],
              'first_release': (1959, 12, 21),
              'names': {'de': 'Hannibal', 'en': 'Hannibal', 'it': 'Annibale'}},
 'Q15857347': {'actors': [('Q243430', 'Terence Hill')],
               'first_release': (2009, 1, 1),
               'names': {'de': 'Doc West – Nobody schlägt zurück',
                         'en': 'Triggerman',
                         'it': ''}},
 'Q1629592': {'actors': [('Q221074', 'Bud Spencer')],
              'first_release': (1957, 1, 1),
              'names': {'de': 'In einem anderen Land',
                        'en': 'A Farewell to Arms',
                        'it': 'Addio alle armi'}},
 'Q16695037': {'actors': [('Q221074', 'Bud Spencer')],
               'first_release': (1992, 1, 1),
               'names': {'de': 'Zwei Supertypen in Miami – Extralarge gegen '
                               'Tod und Teufel',
                         'en': 'Extralarge: Black Magic',
                         'it': ''}},
 'Q1747484': {'actors': [('Q221074', 'Bud Spencer')],
              'first_release': (1969, 9, 9),
              'names': {'de': 'Die im Dreck krepieren',
                        'en': 'The Fifth Day of Peace',
                        'it': 'Gott mit uns (Dio è con noi)'}},
 'Q1788153': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1958, 1, 1),
              'names': {'de': 'Kreuz und Schwert',
                        'en': 'The Sword and the Cross',
                        'it': 'La spada e la croce'}},
 'Q180638': {'actors': [('Q221074', 'Bud Spencer'),
                        ('Q243430', 'Terence Hill')],
             'first_release': (1978, 10, 28),
             'names': {'de': 'Zwei sind nicht zu bremsen',
                       'en': 'Odds and Evens',
                       'it': 'Pari e dispari'}},
 'Q20004776': {'actors': [('Q243430', 'Terence Hill')],
               'first_release': (1953, 1, 1),
               'names': {'de': 'Erste Liebe',
                         'en': 'Too Young for Love',
                         'it': "L'età dell'amore"}},
 'Q2046014': {'actors': [('Q221074', 'Bud Spencer')],
              'first_release': (2001, 1, 1),
              'names': {'de': 'Padre Speranza – Mit Gottes Segen',
                        'en': 'Father Hope',
                        'it': 'Padre Speranza'}},
 'Q231967': {'actors': [('Q221074', 'Bud Spencer'),
                        ('Q243430', 'Terence Hill')],
             'first_release': (1981, 1, 1),
             'names': {'de': 'Zwei Asse trumpfen auf',
                       'en': 'A Friend Is a Treasure',
                       'it': 'Chi trova un amico, trova un tesoro'}},
 'Q232044': {'actors': [('Q221074', 'Bud Spencer'),
                        ('Q243430', 'Terence Hill')],
             'first_release': (1972, 12, 22),
             'names': {'de': 'Zwei Himmelhunde auf dem Weg zur Hölle',
                       'en': 'All the Way, Boys',
                       'it': '...più forte ragazzi!'}},
 'Q232083': {'actors': [('Q221074', 'Bud Spencer'),
                        ('Q243430', 'Terence Hill')],
             'first_release': (1974, 12, 21),
             'names': {'de': 'Zwei Missionare',
                       'en': 'Two Missionaries',
                       'it': "Porgi l'altra guancia"}},
 'Q232166': {'actors': [('Q221074', 'Bud Spencer'),
                        ('Q243430', 'Terence Hill')],
             'first_release': (1977, 4, 1),
             'names': {'de': 'Zwei außer Rand und Band',
                       'en': 'Crime Busters',
                       'it': 'I due superpiedi quasi piatti'}},
 'Q232175': {'actors': [('Q221074', 'Bud Spencer'),
                        ('Q243430', 'Terence Hill')],
             'first_release': (1983, 9, 1),
             'names': {'de': 'Zwei bärenstarke Typen',
                       'en': 'Go for It',
                       'it': 'Nati con la camicia'}},
 'Q232261': {'actors': [('Q221074', 'Bud Spencer'),
                        ('Q243430', 'Terence Hill')],
             'first_release': (1974, 3, 29),
             'names': {'de': 'Zwei wie Pech und Schwefel',
                       'en': "Watch Out, We're Mad!",
                       'it': '...altrimenti ci arrabbiamo!'}},
 'Q250628': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (1977, 3, 3),
             'names': {'de': 'Mister Billion',
                       'en': 'Mr. Billion',
                       'it': 'Mister Miliardo'}},
 'Q2527933': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1997, 1, 1),
              'names': {'de': 'Virtual Weapon',
                        'en': 'Virtual Weapon',
                        'it': 'Potenza virtuale'}},
 'Q256901': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (2005, 1, 1),
             'names': {'de': "L'uomo che sognava con le aquile",
                       'en': 'The Man who Dreamt with Eagles',
                       'it': "L'uomo che sognava con le aquile"}},
 'Q27590220': {'actors': [('Q221074', 'Bud Spencer')],
               'first_release': (1957, 1, 1),
               'names': {'de': '',
                         'en': "Mamma's Boy",
                         'it': 'Il cocco di mamma'}},
 'Q28064472': {'actors': [('Q243430', 'Terence Hill')],
               'first_release': (1979, 1, 1),
               'names': {'de': 'Org', 'en': 'Org', 'it': 'Org'}},
 'Q2940586': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1959, 1, 1),
              'names': {'de': 'Karthago in Flammen',
                        'en': 'Carthage in Flames',
                        'it': 'Cartagine in fiamme'}},
 'Q3053517': {'actors': [('Q221074', 'Bud Spencer')],
              'first_release': (2003, 1, 1),
              'names': {'de': '',
                        'en': 'Singing Behind Screens',
                        'it': 'Cantando dietro i paraventi'}},
 'Q30807542': {'actors': [('Q221074', 'Bud Spencer')],
               'first_release': (1992, 1, 1),
               'names': {'de': 'Zwei Supertypen in Miami – Die Formel des '
                               'Todes',
                         'en': 'Extralarge: Moving Target',
                         'it': 'Detective Extralarge: Bersaglio mobile'}},
 'Q30809518': {'actors': [('Q221074', 'Bud Spencer')],
               'first_release': (1993, 1, 1),
               'names': {'de': 'Zwei Supertypen in Miami – Extralarge und die '
                               'Indianer',
                         'en': 'Extralarge: Indians',
                         'it': ''}},
 'Q30889321': {'actors': [('Q243430', 'Terence Hill')],
               'first_release': (2018, 1, 1),
               'names': {'de': 'Mein Name ist Somebody',
                         'en': 'My Name Is Thomas',
                         'it': 'La chiamavano Maryam'}},
 'Q3108858': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1955, 1, 1),
              'names': {'de': 'Die Verirrten',
                        'en': 'The Abandoned',
                        'it': 'Gli sbandati'}},
 'Q316151': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (1965, 1, 1),
             'names': {'de': 'Old Surehand 1. Teil',
                       'en': 'Old Surehand',
                       'it': 'Surehand - Mano veloce'}},
 'Q3203227': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1960, 1, 1),
              'names': {'de': '',
                        'en': 'The Story of Joseph and His Brethren',
                        'it': 'Giuseppe venduto dai fratelli'}},
 'Q3213477': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1955, 1, 1),
              'names': {'de': 'Wandel des Herzens',
                        'en': 'Golden Vein',
                        'it': "La vena d'oro"}},
 'Q3223684': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1963, 1, 1),
              'names': {'de': '',
                        'en': 'The Shortest Day',
                        'it': 'Il giorno più corto'}},
 'Q3224443': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1959, 1, 1),
              'names': {'de': '',
                        'en': 'Il padrone delle ferriere',
                        'it': 'Il padrone delle ferriere'}},
 'Q324529': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1968, 1, 1),
             'names': {'de': 'Die letzte Rechnung zahlst du selbst',
                       'en': 'Beyond the Law',
                       'it': 'Al di là della legge'}},
 'Q3282673': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1953, 1, 1),
              'names': {'de': '',
                        'en': 'Il viale della speranza',
                        'it': 'Il viale della speranza'}},
 'Q3283372': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1962, 1, 1),
              'names': {'de': 'Pirat der sieben Meere',
                        'en': 'Seven Seas to Calais',
                        'it': 'Il dominatore dei 7 mari'}},
 'Q32999881': {'actors': [('Q221074', 'Bud Spencer'),
                          ('Q243430', 'Terence Hill')],
               'first_release': (2017, 6, 23),
               'names': {'de': 'Sie nannten ihn Spencer',
                         'en': 'They called him Bulldozer',
                         'it': ''}},
 'Q3546248': {'actors': [('Q221074', 'Bud Spencer')],
              'first_release': (1997, 1, 1),
              'names': {'de': 'Al limite',
                        'en': 'To the Limit',
                        'it': 'Al limite'}},
 'Q3547086': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1958, 1, 1),
              'names': {'de': 'Anna von Brooklyn',
                        'en': 'Anna of Brooklyn',
                        'it': 'Anna di Brooklyn'}},
 'Q3664985': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1959, 1, 1),
              'names': {'de': '', 'en': 'Cerasella', 'it': 'Cerasella'}},
 'Q3712040': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1954, 1, 1),
              'names': {'de': 'El Alamein',
                        'en': 'Folgore Division',
                        'it': 'Divisione Folgore'}},
 'Q3744742': {'actors': [('Q221074', 'Bud Spencer')],
              'first_release': (2000, 6, 16),
              'names': {'de': 'Söhne des Windes',
                        'en': 'Hijos del viento',
                        'it': 'Figli del vento'}},
 'Q3754630': {'actors': [('Q221074', 'Bud Spencer')],
              'first_release': (1997, 1, 1),
              'names': {'de': "Fuochi d'artificio",
                        'en': 'Fireworks',
                        'it': "Fuochi d'artificio"}},
 'Q3778078': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1956, 1, 1),
              'names': {'de': '', 'en': '', 'it': 'Guaglione'}},
 'Q3791384': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1956, 1, 1),
              'names': {'de': '', 'en': '', 'it': 'I vagabondi delle stelle'}},
 'Q3801189': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1967, 1, 1),
              'names': {'de': 'Io non protesto, io amo',
                        'en': 'Io non protesto, io amo',
                        'it': 'Io non protesto, io amo'}},
 'Q3811039': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1959, 1, 1),
              'names': {'de': '',
                        'en': "Juke box - Urli d'amore",
                        'it': "Juke-box, urli d'amore"}},
 'Q3819870': {'actors': [('Q221074', 'Bud Spencer')],
              'first_release': (2010, 1, 1),
              'names': {'de': "L'ultimo gattopardo: Ritratto di Goffredo "
                              'Lombardo',
                        'en': "L'ultimo gattopardo: Ritratto di Goffredo "
                              'Lombardo',
                        'it': "L'ultimo gattopardo - Ritratto di Goffredo "
                              'Lombardo'}},
 'Q3822300': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1967, 1, 1),
              'names': {'de': 'Die Helden der Kompanie',
                        'en': 'The Crazy Kids of the War',
                        'it': 'La feldmarescialla'}},
 'Q3822655': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1957, 1, 1),
              'names': {'de': 'Die große blaue Straße',
                        'en': 'La grande strada azzurra',
                        'it': 'La grande strada azzurra'}},
 'Q3828227': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1957, 1, 1),
              'names': {'de': '', 'en': 'Lazzarella', 'it': 'Lazzarella'}},
 'Q3844156': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1956, 1, 1),
              'names': {'de': '', 'en': '', 'it': 'Mamma sconosciuta'}},
 'Q3921867': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1959, 1, 1),
              'names': {'de': 'Junge Leute von heute',
                        'en': 'First Love',
                        'it': 'Primo amore'}},
 'Q3927581': {'actors': [('Q221074', 'Bud Spencer')],
              'first_release': (1950, 1, 1),
              'names': {'de': '',
                        'en': 'Quel fantasma di mio marito',
                        'it': 'Quel fantasma di mio marito'}},
 'Q3960575': {'actors': [('Q221074', 'Bud Spencer')],
              'first_release': (1954, 1, 1),
              'names': {'de': 'Torpedomänner greifen an',
                        'en': 'Siluri umani',
                        'it': 'Siluri umani'}},
 'Q3998121': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (2004, 1, 1),
              'names': {'de': 'Tre giorni d’anarchia',
                        'en': 'Three Days of Anarchy',
                        'it': "Tre giorni d'anarchia"}},
 'Q4003806': {'actors': [('Q221074', 'Bud Spencer')],
              'first_release': (1955, 1, 1),
              'names': {'de': 'Ein Held unserer Tage',
                        'en': 'A Hero of Our Times',
                        'it': 'Un eroe dei nostri tempi'}},
 'Q4003928': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1960, 1, 1),
              'names': {'de': '',
                        'en': 'Un militare e mezzo',
                        'it': 'Un militare e mezzo'}},
 'Q4004077': {'actors': [('Q221074', 'Bud Spencer'),
                         ('Q243430', 'Terence Hill')],
              'first_release': (1976, 1, 1),
              'names': {'de': 'Un sorriso, uno schiaffo, un bacio in bocca',
                        'en': 'Un sorriso, uno schiaffo, un bacio in bocca',
                        'it': 'Un sorriso, uno schiaffo, un bacio in bocca'}},
 'Q4011833': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1953, 1, 1),
              'names': {'de': 'Römischer Reigen',
                        'en': 'It Happened in the Park',
                        'it': 'Villa Borghese'}},
 'Q467379': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (1987, 11, 13),
             'names': {'de': 'Renegade',
                       'en': 'They Call Me Renegade',
                       'it': 'Renegade - Un osso troppo duro'}},
 'Q471775': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (1970, 12, 4),
             'names': {'de': 'Der Teufel kennt kein Halleluja',
                       'en': "The Wind's Fierce",
                       'it': 'La collera del vento'}},
 'Q473803': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1978, 10, 5),
             'names': {'de': 'Sie nannten ihn Mücke',
                       'en': 'Lo chiamavano Bulldozer',
                       'it': 'Lo chiamavano Bulldozer'}},
 'Q473829': {'actors': [('Q221074', 'Bud Spencer'),
                        ('Q243430', 'Terence Hill')],
             'first_release': (1994, 12, 22),
             'names': {'de': 'Die Troublemaker',
                       'en': 'Troublemakers',
                       'it': 'Botte di Natale'}},
 'Q521876': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (1964, 1, 1),
             'names': {'de': 'Winnetou 2. Teil',
                       'en': 'Last of the Renegades',
                       'it': 'Giorni di fuoco'}},
 'Q521907': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (1975, 12, 16),
             'names': {'de': 'Nobody ist der Größte',
                       'en': 'A Genius, Two Partners and a Dupe',
                       'it': 'Un genio, due compari, un pollo'}},
 'Q548277': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1977, 5, 5),
             'names': {'de': 'Charleston – Zwei Fäuste räumen auf',
                       'en': 'Charleston',
                       'it': 'Charleston'}},
 'Q555722': {'actors': [('Q221074', 'Bud Spencer'),
                        ('Q243430', 'Terence Hill')],
             'first_release': (1969, 12, 20),
             'names': {'de': 'Hügel der blutigen Stiefel',
                       'en': 'Boot Hill',
                       'it': 'La collina degli stivali'}},
 'Q558927': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1986, 12, 23),
             'names': {'de': 'Aladin',
                       'en': 'Superfantagenio',
                       'it': 'Superfantagenio'}},
 'Q587854': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1980, 3, 1),
             'names': {'de': 'Plattfuß am Nil',
                       'en': 'Flatfoot in Egypt',
                       'it': "Piedone d'Egitto"}},
 'Q589001': {'actors': [('Q221074', 'Bud Spencer'),
                        ('Q243430', 'Terence Hill')],
             'first_release': (1971, 10, 21),
             'names': {'de': 'Vier Fäuste für ein Halleluja',
                       'en': 'Trinity Is Still My Name',
                       'it': '...continuavano a chiamarlo Trinità'}},
 'Q596199': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1982, 3, 25),
             'names': {'de': 'Banana Joe',
                       'en': 'Banana Joe',
                       'it': 'Banana Joe'}},
 'Q596623': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (1963, 1, 1),
             'names': {'de': 'Der Leopard',
                       'en': 'The Leopard',
                       'it': 'Il Gattopardo'}},
 'Q597579': {'actors': [('Q221074', 'Bud Spencer'),
                        ('Q243430', 'Terence Hill')],
             'first_release': (1984, 10, 19),
             'names': {'de': 'Vier Fäuste gegen Rio',
                       'en': 'Double Trouble',
                       'it': "Non c'è due senza quattro"}},
 'Q598709': {'actors': [('Q221074', 'Bud Spencer'),
                        ('Q243430', 'Terence Hill')],
             'first_release': (1970, 12, 22),
             'names': {'de': 'Die rechte und die linke Hand des Teufels',
                       'en': 'They Call Me Trinity',
                       'it': 'Lo chiamavano Trinità...'}},
 'Q622201': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1971, 1, 1),
             'names': {'de': 'Vier Fliegen auf grauem Samt',
                       'en': 'Four Flies on Grey Velvet',
                       'it': '4 mosche di velluto grigio'}},
 'Q638356': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1972, 12, 27),
             'names': {'de': 'Sie verkaufen den Tod',
                       'en': 'A Reason to Live, a Reason to Die',
                       'it': 'Una ragione per vivere e una per morire'}},
 'Q668928': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1979, 8, 10),
             'names': {'de': 'Der Große mit seinem außerirdischen Kleinen',
                       'en': 'The Sheriff and the Satellite Kid',
                       'it': 'Uno sceriffo extraterrestre... poco extra e '
                             'molto terrestre'}},
 'Q694040': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1978, 3, 22),
             'names': {'de': 'Plattfuß in Afrika',
                       'en': 'Flatfoot in Africa',
                       'it': "Piedone l'africano"}},
 'Q7158603': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1961, 1, 1),
              'names': {'de': '', 'en': 'Pecado de amor', 'it': ''}},
 'Q736144': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (1972, 9, 9),
             'names': {'de': 'Verflucht, verdammt und Halleluja',
                       'en': 'Man of the East',
                       'it': '...E poi lo chiamarono il Magnifico'}},
 'Q751099': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (1991, 7, 4),
             'names': {'de': 'Lucky Luke',
                       'en': 'Lucky Luke',
                       'it': 'Lucky Luke'}},
 'Q758591': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1973, 3, 22),
             'names': {'de': 'Auch die Engel essen Bohnen',
                       'en': 'Even Angels Eat Beans',
                       'it': 'Anche gli angeli mangiano fagioli'}},
 'Q780835': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1981, 3, 6),
             'names': {'de': 'Eine Faust geht nach Westen',
                       'en': 'Buddy Goes West',
                       'it': 'Occhio alla penna'}},
 'Q785492': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (1965, 8, 25),
             'names': {'de': 'Der Ölprinz',
                       'en': 'Rampage at Apache Wells',
                       'it': 'Danza di guerra per Ringo'}},
 'Q7939569': {'actors': [('Q243430', 'Terence Hill')],
              'first_release': (1953, 1, 1),
              'names': {'de': 'Männer ohne Tränen',
                        'en': 'Voice of Silence',
                        'it': 'La voce del silenzio'}},
 'Q822995': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (1965, 1, 1),
             'names': {'de': 'Duell vor Sonnenuntergang',
                       'en': 'Duel at Sundown',
                       'it': 'Sparate a vista su Killer Kid'}},
 'Q825322': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1972, 9, 28),
             'names': {'de': 'Der Sizilianer',
                       'en': 'Black Turin',
                       'it': 'Torino nera'}},
 'Q826950': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (2009, 2, 26),
             'names': {'de': 'Mord ist mein Geschäft, Liebling',
                       'en': 'Mord ist mein Geschäft',
                       'it': 'Tesoro, sono un killer'}},
 'Q840565': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (1967, 1, 1),
             'names': {'de': 'Django und die Bande der Gehenkten',
                       'en': 'Preparati la bara!',
                       'it': 'Preparati la bara!'}},
 'Q841882': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1975, 3, 27),
             'names': {'de': 'Plattfuß räumt auf',
                       'en': 'Flatfoot in Hong Kong',
                       'it': 'Piedone a Hong Kong'}},
 'Q841887': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1973, 10, 23),
             'names': {'de': 'Sie nannten ihn Plattfuß',
                       'en': 'Piedone lo sbirro',
                       'it': 'Piedone lo sbirro'}},
 'Q848252': {'actors': [('Q221074', 'Bud Spencer'),
                        ('Q243430', 'Terence Hill')],
             'first_release': (1968, 10, 31),
             'names': {'de': 'Vier für ein Ave Maria',
                       'en': 'Ace High',
                       'it': "I quattro dell'Ave Maria"}},
 'Q850096': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1980, 9, 25),
             'names': {'de': 'Buddy haut den Lukas',
                       'en': 'Why Did You Pick On Me?',
                       'it': 'Chissà perché... capitano tutte a me'}},
 'Q850155': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1975, 1, 1),
             'names': {'de': 'Hector, der Ritter ohne Furcht und Tadel',
                       'en': 'Il soldato di ventura',
                       'it': 'Il soldato di ventura'}},
 'Q882468': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (1967, 1, 1),
             'names': {'de': 'Blaue Bohnen für ein Halleluja',
                       'en': 'Rita of the West',
                       'it': 'Little Rita nel West'}},
 'Q895543': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (1964, 1, 1),
             'names': {'de': 'Unter Geiern',
                       'en': 'Among Vultures',
                       'it': 'Là dove scende il sole'}},
 'Q908533': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (1983, 1, 1),
             'names': {'de': 'Keiner haut wie Don Camillo',
                       'en': 'The World of Don Camillo',
                       'it': 'Don Camillo'}},
 'Q910695': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (1977, 8, 5),
             'names': {'de': 'Marschier oder stirb',
                       'en': 'March or Die',
                       'it': 'La bandera - Marcia o muori'}},
 'Q917322': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1990, 1, 1),
             'names': {'de': 'Wenn man vom Teufel spricht',
                       'en': 'Speaking of the Devil',
                       'it': 'Un piede in paradiso'}},
 'Q937303': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (1961, 1, 1),
             'names': {'de': 'Aladins Abenteuer',
                       'en': 'The Wonders of Aladdin',
                       'it': 'Le meraviglie di Aladino'}},
 'Q938137': {'actors': [('Q221074', 'Bud Spencer')],
             'first_release': (1951, 1, 1),
             'names': {'de': 'Quo vadis?',
                       'en': 'Quo Vadis',
                       'it': 'Quo vadis'}},
 'Q942657': {'actors': [('Q221074', 'Bud Spencer'),
                        ('Q243430', 'Terence Hill')],
             'first_release': (1985, 11, 1),
             'names': {'de': 'Die Miami Cops',
                       'en': 'Miami Supercops',
                       'it': "Miami Supercops (I poliziotti dell'8ª strada)"}},
 'Q943961': {'actors': [('Q221074', 'Bud Spencer'),
                        ('Q243430', 'Terence Hill')],
             'first_release': (1971, 3, 12),
             'names': {'de': 'Freibeuter der Meere',
                       'en': 'Blackie the Pirate',
                       'it': 'Il corsaro nero'}},
 'Q964009': {'actors': [('Q243430', 'Terence Hill')],
             'first_release': (1973, 12, 13),
             'names': {'de': 'Mein Name ist Nobody',
                       'en': 'My Name is Nobody',
                       'it': 'Il mio nome è Nessuno'}},
 'Q970386': {'actors': [('Q221074', 'Bud Spencer'),
                        ('Q243430', 'Terence Hill')],
             'first_release': (1979, 12, 13),
             'names': {'de': 'Das Krokodil und sein Nilpferd',
                       'en': 'Io sto con gli ippopotami',
                       'it': 'Io sto con gli ippopotami'}}}