expected_zodiac_db = {
 'Aquarius': {'affinities': {'Aries': 0.8, 'Gemini': 1.0, 'Libra': 1.0, 'Sagittarius': 0.8},
              'dates': '21 January-18 February',
              'glyph': '♒︎',
              'house': 11},
 'Aries': {'affinities': {'Aquarius': 0.8, 'Gemini': 0.8, 'Leo': 1.0, 'Sagittarius': 1.0},
           'dates': '21 March-20 April',
           'glyph': '♈︎',
           'house': 1},
 'Cancer': {'affinities': {'Pisces': 1.0, 'Scorpius': 1.0, 'Taurus': 0.8, 'Virgo': 0.8},
            'dates': '22 June-21 July',
            'glyph': '♋︎',
            'house': 4},
 'Capricornus': {'affinities': {'Pisces': 0.8, 'Scorpius': 0.8, 'Taurus': 1.0, 'Virgo': 1.0},
                 'dates': '22 December-20 January',
                 'glyph': '♑︎',
                 'house': 10},
 'Gemini': {'affinities': {'Aquarius': 1.0, 'Aries': 0.8, 'Leo': 0.8, 'Libra': 1.0},
            'dates': '22 May-21 June',
            'glyph': '♊︎',
            'house': 3},
 'Leo': {'affinities': {'Aries': 1.0, 'Gemini': 0.8, 'Libra': 0.8, 'Sagittarius': 1.0},
         'dates': '23 July-23 August',
         'glyph': '♌︎',
         'house': 5},
 'Libra': {'affinities': {'Aquarius': 1.0, 'Gemini': 1.0, 'Leo': 0.8, 'Sagittarius': 0.8},
           'dates': '23 September-23 October',
           'glyph': '♎︎',
           'house': 7},
 'Pisces': {'affinities': {'Cancer': 1.0, 'Capricornus': 0.8, 'Scorpius': 1.0, 'Taurus': 0.8},
            'dates': '19 February-20 March',
            'glyph': '♓︎',
            'house': 12},
 'Sagittarius': {'affinities': {'Aquarius': 0.8, 'Aries': 1.0, 'Leo': 1.0, 'Libra': 0.8},
                 'dates': '23 November-21 December',
                 'glyph': '♐︎',
                 'house': 9},
 'Scorpius': {'affinities': {'Cancer': 1.0, 'Capricornus': 0.8, 'Pisces': 1.0, 'Virgo': 0.8},
              'dates': '24 October-22 November',
              'glyph': ' ♏',
              'house': 8},
 'Taurus': {'affinities': {'Cancer': 0.8, 'Capricornus': 1.0, 'Pisces': 0.8, 'Virgo': 1.0},
            'dates': '21 April-21 May',
            'glyph': '♉︎',
            'house': 2},
 'Virgo': {'affinities': {'Cancer': 0.8, 'Capricornus': 1.0, 'Scorpius': 0.8, 'Taurus': 1.0},
           'dates': '24 August-22 September',
           'glyph': '♍︎',
           'house': 6}}

